# 开发模式,debug, release, test
runmode: debug
# HTTP服务绑定端口
addr: :8080
# API服务名称
name: apiserver
# 检查函数请求的API服务器的地址
url: http://127.0.0.1:8080
# 检查服务器是否正常运行的重试次数，如果访问成功，则不会重试
max_ping_count: 10
# JWT的部署密码
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
# 日志设置
log:
  writers: stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
# 数据库设置
db:
  name: nebula
  addr: 127.0.0.1:3306
  username: root
  password: 123456